### ISSUE TITLE
How should I process empty fields ?

### ISSUE THREAD

**Issue by JanLaureys** [karens/import_drupal#4]
What is the easiest/cleanest way to process fields that are empty sometimes. For example I have a node type `service` with a field `field_intro`.

Most of the time this field is just an array `['value' => '<p>Intro</p>', 'format' =>'filtered_html']`.

I use the extract plugin to get the value and format as shown in the examples, but when the intro is not filled in jsonapi module returns `field_intro: null` and the extract plugin fails.

I've tried a lot of stuff with default_value plugin and array_reset stuff but I can't seem to get it working.

I would also be nice to have an example in this module on how to handle that situation.

**Comment by JanLaureys** [comment]
Solved it myself.

```
  field_intro/value:
    -
      plugin: get
      source: 'field_intro/value'
    -
      plugin: default_value
      default_value: ''
```
